#! /bin/sh

function usage(){

    echo "Usage: $0 [OPTIONS]                           "
    echo "-s --setup        Create configuration data   "
    echo "-h, --help        Display this help and exit. "
}

ARIA_HOME=src/
CONFIG_FILE=${HOME}/.aria/config.ini
if [ $# -eq 0 ] ; then
    if [ -f $CONFIG_FILE ];then
	echo 'Loading aria...'
        /usr/bin/env python2 ${ARIA_HOME}/main.py
        exit 0
    else
	echo 'No configuration file found'
	echo 'Running Setup'
        /usr/bin/env python2 ${ARIA_HOME}/ariasetup.py
	/usr/bin/env python2 ${ARIA_HOME}/main.py
        exit 0
    fi
fi

if [ $# -gt 1 ] ; then
    usage
    exit 0
fi

case "$1" in
    --setup|-s)
        /usr/bin/env python2 ${ARIA_HOME}/ariasetup.py
        exit 0
	;;
    --help|-h|*)
        usage
        exit 0
	;;
esac

