#! /bin/sh

function usage(){

    echo "Usage: $0 [DESTDIR]                           "
    echo "install ARIA client                           "
}

if [ $# -gt 1 ] ; then
    usage
    exit 1
fi

if [ $# -eq 0 ] ; then
	DESTDIR=""
else
	DESTDIR="$1"
fi

echo "Starting..."

sed s_HOME=src/_HOME=/usr/share/aria-client/_ -i aria
echo "Creating Directory...."
install -d ${DESTDIR}/usr/share/aria-client/ && \
echo -e "\tCreated"

echo "Copying files...."
cp -r src/* ${DESTDIR}/usr/share/aria-client/ && \
rm -R ${DESTDIR}/usr/share/aria-client/other && \
rm -R ${DESTDIR}/usr/share/aria-client/ui_files && \
install --mode=755 -D aria ${DESTDIR}/usr/bin/aria-client && \
echo -e "\tFinished"