#! /bin/sh

usage="\
Usage: $0 [DESTDIR]

install ARIA client
if DESTDIR is given aria-client will be install into DESTDIR,
else aria-client will be install into '/'
"

DATADIR="/usr/share/aria-client"
BINDIR="/usr/bin"
CURRDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -gt 1 ] ; then
    echo "$usage"
    exit 1
fi

if [ $# -eq 0 ] ; then
	DESTDIR=""
	if [ $UID -ne 0 ] ;then
		echo "Error: you cannot perform this operation unless you are root"
		exit 1
	fi
else
	DESTDIR="$1"
fi

echo "Starting..."
sed s_HOME=src/_HOME=/usr/share/aria-client/_ -i ${CURRDIR}/aria
echo "Creating Directory...."
install -d ${DESTDIR}/usr/share/aria-client/ && \
echo -e "\tCreated"

echo "Copying files...."
cp -r ${CURRDIR}/src/* ${DESTDIR}${DATADIR}/ && \
rm -R ${DESTDIR}${DATADIR}/other && \
rm -R ${DESTDIR}${DATADIR}/ui_files && \
install --mode=755 -D ${CURRDIR}/aria ${DESTDIR}${BINDIR}/aria-client && \
echo -e "\tFinished"
exit 0
